#!/usr/bin/env python
"""Build the Zenodo upload bundle.

python scripts/package_zenodo.py --results results --assets paper_assets --out zenodo_bundle

Produces
  zenodo_bundle/feddac-code-v1.0.0.zip      source code (feddac/, scripts/, runpod/, tests/, docs)
  zenodo_bundle/feddac-results-v1.0.0.zip   every per-run JSON result, worker/run logs, grouping analysis
  zenodo_bundle/feddac-models-v1.0.0.zip    trained global models (state_dict .pt) + MODELS.md index
  zenodo_bundle/feddac-paper-assets-v1.0.0.zip  LaTeX tables, CSV summary, PDF figures used in the paper
  zenodo_bundle/.zenodo.json, README.md, CHECKSUMS.sha256
"""
import argparse
import glob
import hashlib
import json
import os
import shutil
import zipfile

VERSION = "1.0.0"
CODE_ITEMS = ["feddac", "scripts", "runpod", "tests", "configs/README.md", "README.md", "LICENSE",
              "CITATION.cff", "requirements.txt", ".zenodo.json"]


def zipdir(zpath, items, root="."):
    with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as z:
        for it in items:
            p = os.path.join(root, it)
            if os.path.isdir(p):
                for dp, _, fs in os.walk(p):
                    for f in fs:
                        if "__pycache__" in dp or f.endswith(".pyc"):
                            continue
                        full = os.path.join(dp, f)
                        z.write(full, os.path.relpath(full, root))
            elif os.path.exists(p):
                z.write(p, os.path.relpath(p, root))


def sha256(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def main():
    a = argparse.ArgumentParser()
    a.add_argument("--results", default="results")
    a.add_argument("--logs", default="logs")
    a.add_argument("--assets", default="paper_assets")
    a.add_argument("--out", default="zenodo_bundle")
    a = a.parse_args()
    os.makedirs(a.out, exist_ok=True)
    zipdir(os.path.join(a.out, f"feddac-code-v{VERSION}.zip"), CODE_ITEMS)

    res_items = [d for d in glob.glob(os.path.join(a.results, "*")) if os.path.basename(d) != "models"]
    with zipfile.ZipFile(os.path.join(a.out, f"feddac-results-v{VERSION}.zip"), "w", zipfile.ZIP_DEFLATED) as z:
        for d in res_items:
            for dp, _, fs in os.walk(d):
                for f in fs:
                    full = os.path.join(dp, f)
                    z.write(full, os.path.join("results", os.path.relpath(full, a.results)))
        if os.path.isdir(a.logs):
            for dp, _, fs in os.walk(a.logs):
                for f in fs:
                    full = os.path.join(dp, f)
                    z.write(full, os.path.join("logs", os.path.relpath(full, a.logs)))

    models = sorted(glob.glob(os.path.join(a.results, "models", "*", "*.pt")))
    index = ["# Trained global models", "", "State dicts of the final global model (PyTorch `torch.save`).",
             "Load with `feddac.models.build_model(dataset, num_classes)` and `load_state_dict`.",
             "ResNet-18-GN weights (CIFAR-100, Tiny-ImageNet) are stored in float16.", "",
             "| file | experiment | dataset | method | final acc (%) |", "|---|---|---|---|---|"]
    for m in models:
        exp = os.path.basename(os.path.dirname(m))
        rid = os.path.basename(m)[:-3]
        js = os.path.join(a.results, exp, rid + ".json")
        acc = json.load(open(js))["final_acc"] if os.path.exists(js) else float("nan")
        index.append(f"| {exp}/{rid}.pt | {exp} | {rid.split('_')[0]} | {rid.split('_')[1]} | {acc:.2f} |")
    with zipfile.ZipFile(os.path.join(a.out, f"feddac-models-v{VERSION}.zip"), "w", zipfile.ZIP_DEFLATED) as z:
        for m in models:
            z.write(m, os.path.relpath(m, a.results))
        z.writestr("MODELS.md", "\n".join(index) + "\n")

    if os.path.isdir(a.assets):
        zipdir(os.path.join(a.out, f"feddac-paper-assets-v{VERSION}.zip"), [a.assets])

    shutil.copy(".zenodo.json", os.path.join(a.out, ".zenodo.json"))
    readme = f"""# FedDAC - code, results and trained models (v{VERSION})

Companion archive of the revised manuscript "FedDAC: Federated Learning with Distribution
Anonymization through Clustering on non-IID Data".

| file | content |
|---|---|
| feddac-code-v{VERSION}.zip | complete source code; see README.md inside for usage |
| feddac-results-v{VERSION}.zip | one JSON file per training run (config, per-round accuracy/F1/loss, groups, costs, DP accounting, attack outputs) and the run logs |
| feddac-models-v{VERSION}.zip | trained global models ({len(models)} files) with an index (MODELS.md) |
| feddac-paper-assets-v{VERSION}.zip | the LaTeX tables, CSV summary and figures of the paper, generated by scripts/aggregate.py |

Reproduce all tables: `python scripts/aggregate.py --results results --out paper_assets`.
Licence: code MIT; results and models CC-BY-4.0.
"""
    open(os.path.join(a.out, "README.md"), "w").write(readme)
    with open(os.path.join(a.out, "CHECKSUMS.sha256"), "w") as f:
        for p in sorted(glob.glob(os.path.join(a.out, "*.zip"))):
            f.write(f"{sha256(p)}  {os.path.basename(p)}\n")
    print("bundle written to", a.out, "models:", len(models))


if __name__ == "__main__":
    main()
